/*CREATE DATABASE employes CHARACTER SET UTF8MB4; */

/*CREATE TABLE dept (deptno INT NOT NULL PRIMARY KEY, dname VARCHAR(100) NOT NULL, loc VARCHAR(200) NOT NULL);*/




/*CREATE TABLE emp (empno INT NOT NULL PRIMARY KEY, ename VARCHAR(100) NOT NULL,job VARCHAR(100) NOT NULL,mgr INT,hiredate date NOT NULL, sal DECIMAL(11,2) NOT NULL,
comm DECIMAL(11,2) null,deptno INT NOT NULL,CONSTRAINT FK_dept FOREIGN KEY(deptno) REFERENCES dept(deptno));*/

ALTER TABLE emp ADD CONSTRAINT fk_empno FOREIGN KEY (mgr) REFERENCES emp(empno);